defaults:
  - env_vars: env_vars
  - _self_

seed: 42
window_size: 10
goal_window_size: 10
eval_window_size: 10
batch_size: 1024
epochs: 1000
eval_freq: 10
eval_on_env_freq: 1
num_env_evals: 20
num_final_evals: 20
num_final_eval_per_goal: 5
action_window_size: 5
sequentially_select: false
action_mode: "f"
visual_input: false # true: image-based policy, false: state-based policy
# normalization scale= 10
# vqvae_load_dir: "/home/anqiao/MasterThesis/Checkpoints/VQ-BeT/checkpoints/oven/2024-03-31/21-54-19/pretrain_oven/trained_vqvae.pt"
# normalization scale = 1
# vqvae_load_dir: "/home/anqiao/MasterThesis/Checkpoints/VQ-BeT/checkpoints/kitchen-v0/2024-03-28/00-32-31/effortless-frog-6/trained_vqvae.pt"
# full state
vqvae_load_dir: "/home/anqiao/MasterThesis/Checkpoints/VQ-BeT/checkpoints/oven/2024-04-03/19-44-48/pretrain_oven/trained_vqvae.pt"
goal_dim: 0

wandb:
  project: "vq-bet"
  entity: ${env_vars.wandb_entity}

device: cuda
optim:
  lr: 5.5e-5
  weight_decay: 2e-4
  betas: [0.9, 0.999]

env:
  gym:
    _target_: kitchen_env.KitchenWrapper
    id: kitchen-v0
    env:
      _target_: gym.make
      id: kitchen-v0
    visual_input: ${visual_input}
  obs_dim: 32
  act_dim: 32
  goal_dim: ${goal_dim}

data:
  _target_: dataset.get_alma_train_val
  # data_directory: ${env_vars.datasets.oven}
  data_directory: /home/anqiao/MasterThesis/Data/OvenOpening/pt/output_fullstate
  goal_conditional: future
  window_size: ${window_size}
  future_seq_len: ${goal_window_size}
  min_future_sep: ${action_window_size}
  action_window_size: ${action_window_size}
  vqbet_get_future_action_chunk: true
  padding: "None"
  noise_enhance_coe: 0.01

save_every: 10
save_path: "${env_vars.save_path}/checkpoints/${env.gym.id}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
# load_path:  "/home/anqiao/MasterThesis/Checkpoints/VQ-BeT/checkpoints/kitchen-v0/2024-04-02/20-56-20/sleek-pond-23"
# load_path:  "/home/anqiao/MasterThesis/Checkpoints/VQ-BeT/checkpoints/kitchen-v0/2024-04-03/11-50-56/pious-puddle-28"
# load_path: "/home/anqiao/MasterThesis/Checkpoints/VQ-BeT/checkpoints/kitchen-v0/2024-04-03/12-01-17/breezy-firefly-30"
# load_path: "/home/anqiao/MasterThesis/Checkpoints/VQ-BeT/checkpoints/kitchen-v0/2024-04-03/14-32-04/dark-darkness-42"
# load_path: "/home/anqiao/MasterThesis/Checkpoints/VQ-BeT/checkpoints/kitchen-v0/2024-04-03/14-32-04/dark-darkness-42"
# load_path: "/home/anqiao/MasterThesis/Checkpoints/VQ-BeT/checkpoints/kitchen-v0/2024-04-03/15-30-42/dashing-fire-44"
load_path: None


model:
  _target_: vq_behavior_transformer.BehaviorTransformer
  obs_dim: ${env.obs_dim}
  act_dim: ${env.act_dim}
  goal_dim: ${env.goal_dim}
  obs_window_size: ${window_size}
  act_window_size: ${action_window_size}
  sequentially_select: ${sequentially_select}
  gpt_model:
    _target_: vq_behavior_transformer.GPT
    config:
      _target_: vq_behavior_transformer.GPTConfig
      block_size: 110
      input_dim: ${env.obs_dim}
      n_layer: 6
      n_head: 6
      n_embd: 120
  vqvae_model:
    _target_: vqvae.VqVae
    obs_dim: 32
    input_dim_h: ${action_window_size}
    input_dim_w: ${env.act_dim}
    n_latent_dims: 512
    vqvae_n_embed: 16
    vqvae_groups: 2
    eval: true
    device: ${device}
    load_dir: ${vqvae_load_dir}
    act_scale: 1
  offset_loss_multiplier: 100
  secondary_code_multiplier: 1

goal_fn:
  _target_: kitchen_env.get_goal_fn
  data_directory: ${env_vars.datasets.relay_kitchen}
  goal_conditional: ${data.goal_conditional}
  seed: ${seed}
  train_fraction: 0.95
  goal_seq_len: ${goal_window_size}
  unconditional: false
  goal_dim: ${goal_dim}
  visual_input: ${visual_input}
